# .github/workflows/docker-publish.yml
name: Build, Scan and Push to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required for GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/nginx-image:latest .

    - name: Download Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner

    - name: Scan Docker image with Sysdig
      env:
        SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
      run: |
        ./sysdig-cli-scanner --apiurl https://app.me2.sysdig.com/ ghcr.io/${{ github.repository_owner }}/nginx-image:latest

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/nginx-image:latest

